### ISSUE TITLE
How to extract features using CLIP VIT-L?

### ISSUE THREAD

**Issue by yuanrr** [mlvlab/Flipped-VQA#1]
I used CLIP to extract video features on my own dataset, but `qav_loss` did not decrease at all. I tried the provided features on the Next-QA dataset and found the `qav_loss` can converge in 5 epochs. I don't know why...
I would like to ask if you can provide the code of the feature extraction part, thank you very much...

**Comment by ikodoh** [comment]
Thank you for your interests of our work.
We extracted CLIP feature using the code from [FrozenBiLM](https://github.com/antoyang/FrozenBiLM).
You can refer to 'Video Feature Extraction' part from the above repository.
Also, if your own dataset does not have temporal dynamics in the video, ```qav_loss``` may not decrease.
If you have any questions, please let me know.

**Comment by yuanrr** [comment]
Thank you very much for your reply! I will try it.
