### ISSUE TITLE
About the tokenizer!!!

### ISSUE THREAD

**Issue by Yuzuriha-Inori-x** [mlvlab/Flipped-VQA#20]
Hi, I want to ask, what are the values ​​of self.v_token_id = 15167, self.q_token_id = 16492, self.a_token_id = 22550, self.nl_id = 13 in tokenizer set based on? Or why is the value of v_token_id set to 15167?

**Comment by ikodoh** [comment]
Hi,

Thank you for your interest in our work.
v_token_id, q_token_id, a_token_id, and nl_id stand for the tokenized id of the word 'Video', 'Question', 'Answer', and '\n' (next line), respectively.
I set those tokens to identify which positions to start the generation.
Also, those token ids are set based on LLaMA Tokenizer, so if you want to use a different LLM, you have to change those token ids according to the LLM.

**Comment by Yuzuriha-Inori-x** [comment]
Hi, thank you for your help! 
I have another question! In the code, you load the "tokenizer.model" file. How do you find the token ID corresponding to the words?Such as: "Audio", "One" ？

**Comment by ikodoh** [comment]
I manually input the word in the 'self.sp_model'. 
For example, the output of self.sp_model.encode('Audio') is the token ID for the word 'Audio'.
