### ISSUE TITLE
Where is the `clipvitl14.pth` for the TVQA dataset?

### ISSUE THREAD

**Issue by chuanwise** [mlvlab/Flipped-VQA#21]
According to `data` folder for the TVQA dataset: <https://drive.google.com/drive/folders/1cOyump1lbEc_IICeJ79K9nXEUa2p9MZm>, there is no such file called `clipvitl14.pth`.

**Comment by ikodoh** [comment]
Hi, 

Thank you for your interest in our work.
I have uploaded the ```clipvitl14.pth``` at the [huggingface](https://huggingface.co/datasets/ikodoh/Flipped-VQA).
Sorry for the inconvenience.
If there is any problem, please let me know.

Thank you.

**Comment by ikodoh** [comment]
Hi,

Thank you for your interest in our work.
I have uploaded the clipvitl14.pth at the [huggingface](https://huggingface.co/datasets/ikodoh/Flipped-VQA).
Sorry for the inconvenience.
If there is any problem, please let me know.

Thank you.

**Comment by ikodoh** [comment]
Hi,
Thank you for your interest in our work.
I have uploaded the ```clipvitl14.pth``` of the TVQA at the [huggingface](https://huggingface.co/datasets/ikodoh/Flipped-VQA-Data).
Sorry for the inconvenience.
If there is any problem, please let me know.
Thank you.

**Comment by chuanwise** [comment]
![QQ_1722154147156](https://github.com/user-attachments/assets/628de24e-0602-44b7-a69c-c6b5e24806cd)

```
Internal Error - We're working hard to fix this as soon as possible!
```

**Comment by ikodoh** [comment]
I think it is a temporary issue of huggingface.
However, the below command still works.
```git lfs install
git clone https://huggingface.co/datasets/ikodoh/Flipped-VQA-Data
mv ./Flipped-VQA-Data/data ./
mv ./Flipped-VQA-Data/checkpoint ./
unzip ./data/tvqa/tvqa_subtitles.zip -d ./data/tvqa
rm -rf Flipped-VQA-Data ./data/tvqa/tvqa_subtitles.zip```

**Comment by chuanwise** [comment]
Thank you very much! But I found that my GPU hasn't so many memory to load any official version of LLaMA, and I the files of downloaded 4-bit version (only requires about 4G GPU memory) are different with your codes 😭...
