### ISSUE TITLE
How to use a trained checkpoint to make inference on validation set and resume from checkpoint.

### ISSUE THREAD

**Issue by iquibalh** [mlvlab/Flipped-VQA#3]
I have trained a model and saved the checkpoint_best.pth, (for nextqa) now, how to use this checkpoint to run inference on the validation dataset? And how to use this trained checkpoint to resume the training process?
**Folder structure**
> ./pretrained
>    └─ llama
>        |─ 7B
>        |   |─ consolidated.00.pth
>        |   └─ params.json
>        |─ 13B
>        |   :
>        |─ 33B
>        |   :
>        └─ tokenizer.model
> ./data
>    |─ nextqa
>    |   |─ train.csv
>    |   |─ val.csv
>    |   └─ clipvitl14.pth
>    :
> ./checkpoint
>    |─ nextqa
>    |   |─ checkpoint_best.pth
>    |   |─ log.txt
>    :

**Comment by ikodoh** [comment]
You can simply add ```--resume ./checkpoint/nextqa/checkpoint_best.pth``` to your running command to resume the training or run inference.

**Comment by iquibalh** [comment]
I did tried with the --resume option before posting. But it trows an error about missing keys in state_dict loaded from misc.load_model:
```
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    main(args)
  File "train.py", line 121, in main
    misc.load_model(args=args, model_without_ddp=model_without_ddp, optimizer=optimizer, loss_scaler=loss_scaler)
  File "/home/admin-guest/Documents/multimodal-ml/iqui/Flipped-VQA/util/misc.py", line 302, in load_model
    model_without_ddp.load_state_dict(checkpoint['model'])
  File "/home/admin-guest/anaconda3/envs/flippedvqa_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Transformer:
	Missing key(s) in state_dict: "tok_embeddings.weight", "layers.0.attention.wq.weight", "layers.0.attention.wk.weight", "layers.0.attention.wv.weight", "layers.0.attention.wo.weight", "layers.0.feed_forward.w1.weight", "layers.0.feed_forward.w2.weight", "layers.0.feed_forward.w3.weight", "layers.0.attention_norm.weight", "layers.0.ffn_norm.weight", "layers.1.attention.wq.weight", "layers.1.attention.wk.weight", "layers.1.attention.wv.weight", "layers.1.attention.wo.weight", "layers.1.feed_forward.w1.weight", "layers.1.feed_forward.w2.weight"...
```

**Comment by ikodoh** [comment]
Saved checkpoint only contains trainable parameters, so you need to set ```strict=False``` in ```model_without_ddp.load_state_dict(checkpoint['model'], strict=False)```. 
Please pull our code again.

**Comment by Huangbukun** [comment]
> Saved checkpoint only contains trainable parameters, so you need to set `strict=False` in `model_without_ddp.load_state_dict(checkpoint['model'], strict=False)`. Please pull our code again.

I tried it, but it still doesn’t work. If I directly load the weight file after finetune without changing the epoch, the process will be terminated directly and no inference will be performed.

**Comment by ikodoh** [comment]
This is because the loaded epoch of the checkpoint is the same as the total epoch.
You may load checkpoint without the epoch or increasing the total epoch.
