### ISSUE TITLE
What is the function of the parameter `max_feats`?

### ISSUE THREAD

**Issue by kuhne12** [mlvlab/Flipped-VQA#7]
Thank you for the great work and open source code!

I have been exploring the codebase and documentation, and I came across the `max_feats` parameter. However, I couldn't find a clear explanation for its purpose. Could you please provide some insights into what role `max_feats` plays in the functionality of the project?

Thank you in advance for taking the time to address this inquiry.

**Comment by ikodoh** [comment]
Thanks for your interest in our work.
```max_feats``` denotes the maximum number of frames.
The larger ```max_feats``` generally yields the higher performance.
